/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiCreateNewMealRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiCreateNewMealRequestMessage (0 custom class methods, 6 custom properties)

#import "GTLMealServiceApisMealApiCreateNewMealRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiCreateNewMealRequestMessage
//

@implementation GTLMealServiceApisMealApiCreateNewMealRequestMessage
@dynamic authToken, emailAddress, endRange, mealType, numPeople, startRange;
@end
