/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiCreateNewMealResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiCreateNewMealResponseMessage (0 custom class methods, 3 custom properties)

#import "GTLMealServiceApisMealApiCreateNewMealResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiCreateNewMealResponseMessage
//

@implementation GTLMealServiceApisMealApiCreateNewMealResponseMessage
@dynamic errorMessage, errorNumber, mealKey;
@end
