/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage (0 custom class methods, 4 custom properties)

#import "GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage
//

@implementation GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage
@dynamic authToken, emailAddress, endRange, startRange;
@end
