/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealService.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals

#import "GTLMealServiceConstants.h"

#import "GTLMealServiceApisMealApiCreateNewMealRequestMessage.h"
#import "GTLMealServiceApisMealApiCreateNewMealResponseMessage.h"
#import "GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage.h"
#import "GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage.h"
#import "GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage.h"
#import "GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage.h"
#import "GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetAllUpcomingMealsResponseMessage.h"
#import "GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage.h"
#import "GTLMealServiceApisMealApiGetMatchedMealsInRangeResponseMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingMatchedMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingMatchedMealsResponseMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage.h"
#import "GTLMealServiceApisMealApiMatchedMealMessage.h"
#import "GTLMealServiceApisMealApiUnMatchedMealMessage.h"

#import "GTLQueryMealService.h"
#import "GTLServiceMealService.h"
