/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage (0 custom class methods, 2 custom properties)

#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage
//

@implementation GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage
@dynamic authToken, emailAddress;
@end
