/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage (0 custom class methods, 2 custom properties)

#import "GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage
//

@implementation GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage
@dynamic authToken, emailAddress;
@end
