/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage
//

@implementation GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage
@dynamic errorMessage, errorNumber;
@end
