/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiUserMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiUserMessage (0 custom class methods, 3 custom properties)

#import "GTLMealServiceApisMealApiUserMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiUserMessage
//

@implementation GTLMealServiceApisMealApiUserMessage
@dynamic firstName, lastName, userKey;
@end
