/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage
//

@interface GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage : GTLObject
@property (nonatomic, copy) NSString *authToken;
@property (nonatomic, copy) NSString *emailAddress;
@property (nonatomic, copy) NSString *mealKey;
@end
