/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals

#import "GTLMealServiceConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeMealServiceUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
