/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiMatchedMealMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiMatchedMealMessage (0 custom class methods, 6 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLMealServiceApisMealApiUserMessage;

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiMatchedMealMessage
//

@interface GTLMealServiceApisMealApiMatchedMealMessage : GTLObject
@property (nonatomic, copy) NSString *matchedDate;
@property (nonatomic, copy) NSString *mealKey;
@property (nonatomic, retain) NSNumber *mealType;  // longLongValue
@property (nonatomic, retain) NSNumber *numPeople;  // longLongValue
@property (nonatomic, retain) NSArray *people;  // of GTLMealServiceApisMealApiUserMessage
@property (nonatomic, copy) NSString *startTime;
@end
