/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiUnMatchedMealMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiUnMatchedMealMessage (0 custom class methods, 6 custom properties)

#import "GTLMealServiceApisMealApiUnMatchedMealMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiUnMatchedMealMessage
//

@implementation GTLMealServiceApisMealApiUnMatchedMealMessage
@dynamic created, creatorKey, endRange, mealType, numPeople, startRange;
@end
