/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage (0 custom class methods, 7 custom properties)

#import "GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage
//

@implementation GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage
@dynamic authToken, emailAddress, endRange, mealKey, mealType, numPeople,
         startRange;
@end
