/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage
//

@implementation GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage
@dynamic errorMessage, errorNumber;
@end
