/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage (0 custom class methods, 3 custom properties)

#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage.h"

#import "GTLMealServiceApisMealApiUnMatchedMealMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage
//

@implementation GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage
@dynamic errorMessage, errorNumber, unMatchedMeals;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"unMatchedMeals" : [GTLMealServiceApisMealApiUnMatchedMealMessage class]
  };
  return map;
}

@end
