/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage
//

@interface GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage : GTLObject
@property (nonatomic, copy) NSString *authToken;
@property (nonatomic, copy) NSString *emailAddress;
@end
