/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQueryUserService.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User
// Classes:
//   GTLQueryUserService (5 custom class methods, 1 custom properties)

#import "GTLQueryUserService.h"

#import "GTLUserServiceApisUserApiLogInUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogInUserResponseMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserResponseMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserRequestMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserResponseMessage.h"
#import "GTLUserServiceApisUserApiValidateUserRequestMessage.h"
#import "GTLUserServiceApisUserApiValidateUserResponseMessage.h"

@implementation GTLQueryUserService

@dynamic fields;

#pragma mark - Service level methods
// These create a GTLQueryUserService object.

+ (instancetype)queryForLoginUserWithObject:(GTLUserServiceApisUserApiLogInUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.loginUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiLogInUserResponseMessage class];
  return query;
}

+ (instancetype)queryForLogoutUserWithObject:(GTLUserServiceApisUserApiLogOutUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.logoutUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiLogOutUserResponseMessage class];
  return query;
}

+ (instancetype)queryForSendNewEmailVerificationWithObject:(GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.sendNewEmailVerification";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage class];
  return query;
}

+ (instancetype)queryForSignupUserWithObject:(GTLUserServiceApisUserApiSignUpUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.signupUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiSignUpUserResponseMessage class];
  return query;
}

+ (instancetype)queryForValidateUserWithObject:(GTLUserServiceApisUserApiValidateUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.validateUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiValidateUserResponseMessage class];
  return query;
}

@end
