/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryUserService.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLQueryUserService (11 custom class methods, 1 custom properties)

#import "GTLQueryUserService.h"

#import "GTLUserServiceApisUserApiAddComplimentRequestMessage.h"
#import "GTLUserServiceApisUserApiAddComplimentResponseMessage.h"
#import "GTLUserServiceApisUserApiAddReportToUserRequestMessage.h"
#import "GTLUserServiceApisUserApiAddReportToUserResponseMessage.h"
#import "GTLUserServiceApisUserApiGetComplimentsGivenByUserRequestMessage.h"
#import "GTLUserServiceApisUserApiGetComplimentsGivenByUserResponseMessage.h"
#import "GTLUserServiceApisUserApiGetComplimentsGivenToUserRequestMessage.h"
#import "GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage.h"
#import "GTLUserServiceApisUserApiIncrementNegativeRatingRequestMessage.h"
#import "GTLUserServiceApisUserApiIncrementNegativeRatingResponseMessage.h"
#import "GTLUserServiceApisUserApiIncrementPositiveRatingRequestMessage.h"
#import "GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage.h"
#import "GTLUserServiceApisUserApiLogInUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogInUserResponseMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserResponseMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserRequestMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserResponseMessage.h"
#import "GTLUserServiceApisUserApiValidateUserRequestMessage.h"
#import "GTLUserServiceApisUserApiValidateUserResponseMessage.h"

@implementation GTLQueryUserService

@dynamic fields;

#pragma mark - Service level methods
// These create a GTLQueryUserService object.

+ (instancetype)queryForAddComplimentWithObject:(GTLUserServiceApisUserApiAddComplimentRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.addCompliment";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiAddComplimentResponseMessage class];
  return query;
}

+ (instancetype)queryForAddReportToUserWithObject:(GTLUserServiceApisUserApiAddReportToUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.addReportToUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiAddReportToUserResponseMessage class];
  return query;
}

+ (instancetype)queryForGetComplimentsGivenByUserWithObject:(GTLUserServiceApisUserApiGetComplimentsGivenByUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.getComplimentsGivenByUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiGetComplimentsGivenByUserResponseMessage class];
  return query;
}

+ (instancetype)queryForGetComplimentsGivenToUserWithObject:(GTLUserServiceApisUserApiGetComplimentsGivenToUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.getComplimentsGivenToUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage class];
  return query;
}

+ (instancetype)queryForIncrementNegativeRatingWithObject:(GTLUserServiceApisUserApiIncrementNegativeRatingRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.incrementNegativeRating";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiIncrementNegativeRatingResponseMessage class];
  return query;
}

+ (instancetype)queryForIncrementPositiveRatingWithObject:(GTLUserServiceApisUserApiIncrementPositiveRatingRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.incrementPositiveRating";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage class];
  return query;
}

+ (instancetype)queryForLoginUserWithObject:(GTLUserServiceApisUserApiLogInUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.loginUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiLogInUserResponseMessage class];
  return query;
}

+ (instancetype)queryForLogoutUserWithObject:(GTLUserServiceApisUserApiLogOutUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.logoutUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiLogOutUserResponseMessage class];
  return query;
}

+ (instancetype)queryForSendNewEmailVerificationWithObject:(GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.sendNewEmailVerification";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage class];
  return query;
}

+ (instancetype)queryForSignupUserWithObject:(GTLUserServiceApisUserApiSignUpUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.signupUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiSignUpUserResponseMessage class];
  return query;
}

+ (instancetype)queryForValidateUserWithObject:(GTLUserServiceApisUserApiValidateUserRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"userService.validateUser";
  GTLQueryUserService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLUserServiceApisUserApiValidateUserResponseMessage class];
  return query;
}

@end
