/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryMealService.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLQueryMealService (7 custom class methods, 1 custom properties)

#import "GTLQueryMealService.h"

#import "GTLMealServiceApisMealApiCreateNewMealRequestMessage.h"
#import "GTLMealServiceApisMealApiCreateNewMealResponseMessage.h"
#import "GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage.h"
#import "GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage.h"
#import "GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage.h"
#import "GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage.h"
#import "GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetAllUpcomingMealsResponseMessage.h"
#import "GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage.h"
#import "GTLMealServiceApisMealApiGetMatchedMealsInRangeResponseMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingMatchedMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingMatchedMealsResponseMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage.h"
#import "GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage.h"

@implementation GTLQueryMealService

@dynamic fields;

#pragma mark - Service level methods
// These create a GTLQueryMealService object.

+ (instancetype)queryForCreateNewMealWithObject:(GTLMealServiceApisMealApiCreateNewMealRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.createNewMeal";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiCreateNewMealResponseMessage class];
  return query;
}

+ (instancetype)queryForDeleteUnMatchedMealWithObject:(GTLMealServiceApisMealApiDeleteUnMatchedMealRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.deleteUnMatchedMeal";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiDeleteUnMatchedMealResponseMessage class];
  return query;
}

+ (instancetype)queryForEditUnMatchedMealWithObject:(GTLMealServiceApisMealApiEditUnMatchedMealRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.editUnMatchedMeal";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiEditUnMatchedMealResponseMessage class];
  return query;
}

+ (instancetype)queryForGetAllUpcomingMealsWithObject:(GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.getAllUpcomingMeals";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiGetAllUpcomingMealsResponseMessage class];
  return query;
}

+ (instancetype)queryForGetMatchedMealsInRangeWithObject:(GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.getMatchedMealsInRange";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiGetMatchedMealsInRangeResponseMessage class];
  return query;
}

+ (instancetype)queryForGetUpcomingMatchedMealsWithObject:(GTLMealServiceApisMealApiGetUpcomingMatchedMealsRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.getUpcomingMatchedMeals";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiGetUpcomingMatchedMealsResponseMessage class];
  return query;
}

+ (instancetype)queryForGetUpcomingUnMatchedMealsWithObject:(GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"mealService.getUpcomingUnMatchedMeals";
  GTLQueryMealService *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage class];
  return query;
}

@end
