/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceMealService.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   mealService/v1.0
// Description:
//   API for dealing with meals
// Classes:
//   GTLServiceMealService (0 custom class methods, 0 custom properties)

#import "GTLMealService.h"

@implementation GTLServiceMealService

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryMealService class],
    [GTLMealServiceApisMealApiCreateNewMealRequestMessage class],
    [GTLMealServiceApisMealApiCreateNewMealResponseMessage class],
    [GTLMealServiceApisMealApiGetAllUpcomingMealsRequestMessage class],
    [GTLMealServiceApisMealApiGetAllUpcomingMealsResponseMessage class],
    [GTLMealServiceApisMealApiGetMatchedMealsInRangeRequestMessage class],
    [GTLMealServiceApisMealApiGetMatchedMealsInRangeResponseMessage class],
    [GTLMealServiceApisMealApiGetUpcomingMatchedMealsRequestMessage class],
    [GTLMealServiceApisMealApiGetUpcomingMatchedMealsResponseMessage class],
    [GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsRequestMessage class],
    [GTLMealServiceApisMealApiGetUpcomingUnMatchedMealsResponseMessage class],
    [GTLMealServiceApisMealApiMatchedMealMessage class],
    [GTLMealServiceApisMealApiUnMatchedMealMessage class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1.0";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://cafbuddy.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
