/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserServiceApisUserApiLogOutUserRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiLogOutUserRequestMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiLogOutUserRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiLogOutUserRequestMessage
//

@implementation GTLUserServiceApisUserApiLogOutUserRequestMessage
@dynamic authToken, emailAddress;
@end
