/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User

#import "GTLUserServiceConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeUserServiceUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
