/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserServiceApisUserApiLogOutUserResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiLogOutUserResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiLogOutUserResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiLogOutUserResponseMessage
//

@implementation GTLUserServiceApisUserApiLogOutUserResponseMessage
@dynamic errorMessage, errorNumber;
@end
