/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiLogInUserResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiLogInUserResponseMessage (0 custom class methods, 5 custom properties)

#import "GTLUserServiceApisUserApiLogInUserResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiLogInUserResponseMessage
//

@implementation GTLUserServiceApisUserApiLogInUserResponseMessage
@dynamic authToken, errorMessage, errorNumber, firstName, lastName;
@end
