/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserServiceApisUserApiValidateUserRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiValidateUserRequestMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiValidateUserRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiValidateUserRequestMessage
//

@implementation GTLUserServiceApisUserApiValidateUserRequestMessage
@dynamic authToken, emailAddress;
@end
