/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserService_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User

#import "GTLUserServiceConstants.m"

#import "GTLUserServiceApisUserApiLogInUserRequestMessage.m"
#import "GTLUserServiceApisUserApiLogInUserResponseMessage.m"
#import "GTLUserServiceApisUserApiLogOutUserRequestMessage.m"
#import "GTLUserServiceApisUserApiLogOutUserResponseMessage.m"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.m"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage.m"
#import "GTLUserServiceApisUserApiSignUpUserRequestMessage.m"
#import "GTLUserServiceApisUserApiSignUpUserResponseMessage.m"
#import "GTLUserServiceApisUserApiValidateUserRequestMessage.m"
#import "GTLUserServiceApisUserApiValidateUserResponseMessage.m"

#import "GTLQueryUserService.m"
#import "GTLServiceUserService.m"
