/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage (0 custom class methods, 1 custom properties)

#import "GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage
//

@implementation GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage
@dynamic emailAddress;
@end
