/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserService.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User

#import "GTLUserServiceConstants.h"

#import "GTLUserServiceApisUserApiAddReportToUserRequestMessage.h"
#import "GTLUserServiceApisUserApiAddReportToUserResponseMessage.h"
#import "GTLUserServiceApisUserApiIncrementNegativeRatingRequestMessage.h"
#import "GTLUserServiceApisUserApiIncrementNegativeRatingResponseMessage.h"
#import "GTLUserServiceApisUserApiIncrementPositiveRatingRequestMessage.h"
#import "GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage.h"
#import "GTLUserServiceApisUserApiLogInUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogInUserResponseMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserRequestMessage.h"
#import "GTLUserServiceApisUserApiLogOutUserResponseMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationRequestMessage.h"
#import "GTLUserServiceApisUserApiSendNewEmailVerificationResponseMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserRequestMessage.h"
#import "GTLUserServiceApisUserApiSignUpUserResponseMessage.h"
#import "GTLUserServiceApisUserApiValidateUserRequestMessage.h"
#import "GTLUserServiceApisUserApiValidateUserResponseMessage.h"

#import "GTLQueryUserService.h"
#import "GTLServiceUserService.h"
