/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage
//

@implementation GTLUserServiceApisUserApiIncrementPositiveRatingResponseMessage
@dynamic errorMessage, errorNumber;
@end
