/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLUserServiceApisUserApiSignUpUserRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.011
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiSignUpUserRequestMessage (0 custom class methods, 4 custom properties)

#import "GTLUserServiceApisUserApiSignUpUserRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiSignUpUserRequestMessage
//

@implementation GTLUserServiceApisUserApiSignUpUserRequestMessage
@dynamic emailAddress, firstName, lastName, password;
@end
