/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage (0 custom class methods, 3 custom properties)

#import "GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage.h"

#import "GTLUserServiceApisUserApiComplimentMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage
//

@implementation GTLUserServiceApisUserApiGetComplimentsGivenToUserResponseMessage
@dynamic compliments, errorMessage, errorNumber;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"compliments" : [GTLUserServiceApisUserApiComplimentMessage class]
  };
  return map;
}

@end
