/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiAddComplimentResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiAddComplimentResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiAddComplimentResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiAddComplimentResponseMessage
//

@implementation GTLUserServiceApisUserApiAddComplimentResponseMessage
@dynamic errorMessage, errorNumber;
@end
