/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiComplimentMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiComplimentMessage (0 custom class methods, 4 custom properties)

#import "GTLUserServiceApisUserApiComplimentMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiComplimentMessage
//

@implementation GTLUserServiceApisUserApiComplimentMessage
@dynamic comment, giverUserKey, mealKey, toUserKey;
@end
