/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiAddReportToUserRequestMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiAddReportToUserRequestMessage (0 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiAddReportToUserRequestMessage
//

@interface GTLUserServiceApisUserApiAddReportToUserRequestMessage : GTLObject
@property (nonatomic, copy) NSString *authToken;
@property (nonatomic, copy) NSString *comments;
@property (nonatomic, copy) NSString *emailAddress;
@property (nonatomic, copy) NSString *fromUserKey;
@property (nonatomic, copy) NSString *mealKey;
@property (nonatomic, retain) NSNumber *reportType;  // longLongValue
@property (nonatomic, retain) NSArray *userKeys;  // of NSString
@end
