/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiAddReportToUserResponseMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiAddReportToUserResponseMessage (0 custom class methods, 2 custom properties)

#import "GTLUserServiceApisUserApiAddReportToUserResponseMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiAddReportToUserResponseMessage
//

@implementation GTLUserServiceApisUserApiAddReportToUserResponseMessage
@dynamic errorMessage, errorNumber;
@end
