/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiAddReportToUserRequestMessage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiAddReportToUserRequestMessage (0 custom class methods, 4 custom properties)

#import "GTLUserServiceApisUserApiAddReportToUserRequestMessage.h"

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiAddReportToUserRequestMessage
//

@implementation GTLUserServiceApisUserApiAddReportToUserRequestMessage
@dynamic authToken, comments, emailAddress, reportType;
@end
