/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLUserServiceApisUserApiComplimentMessage.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   userService/v1.0
// Description:
//   API for working with a User
// Classes:
//   GTLUserServiceApisUserApiComplimentMessage (0 custom class methods, 4 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLUserServiceApisUserApiComplimentMessage
//

@interface GTLUserServiceApisUserApiComplimentMessage : GTLObject
@property (nonatomic, copy) NSString *comment;
@property (nonatomic, copy) NSString *giverUserKey;
@property (nonatomic, copy) NSString *mealKey;
@property (nonatomic, copy) NSString *toUserKey;
@end
